parameters:
    app.notifications.email_sender: anonymous@example.com
    user_entity.class: AppBundle\Entity\User

services:
    # First we define some basic services to make these utilities available in
    # the entire application
    slugger:
        class: AppBundle\Utils\Slugger

    markdown:
        class: AppBundle\Utils\Markdown

    # These are the Twig extensions that create new filters and functions for
    # using them in the templates
    app.twig.app_extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments: ["@markdown"]
        tags:
            - { name: twig.extension }

    app.twig.locale_extension:
        public:    false
        class:     AppBundle\Twig\LocaleExtension
        arguments: ["%app_locales%"]
        tags:
            - { name: twig.extension }

    app.twig.source_code_extension:
        public:    false
        class:     AppBundle\Twig\SourceCodeExtension
        arguments: ["@twig.loader", "%kernel.root_dir%"]
        tags:
            - { name: twig.extension }

    app.twig.extension_intl:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.controller_listener:
        class:     AppBundle\EventListener\ControllerListener
        arguments: ["@app.twig.source_code_extension"]
        tags:
            - { name: 'kernel.event_listener', event: kernel.controller, method: registerCurrentController }

    user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%user_entity.class%]

    user_service:
        class:  AppBundle\Services\UserService
        arguments: [ @user_repository ]

    security.access.post_voter:
        class:      AppBundle\Security\Authorization\Voter\PostVoter
        public:     false
        tags:
            - { name: security.voter }
